name: AuditTrail

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8050:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge