name: AuditTrail

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8050:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/usr/src/app
    stdin_open: true
    tty: true
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - ./auth-service/.env
    volumes:
      - ./auth-service:/var/www
    depends_on:
      - mysql
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - app-network
    env_file:
      - ./backend/.env

  mysql:
    image: mysql:latest
    container_name: mysql-audit
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - ${MYSQL_EXTERNAL_PORT}:3306
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    env_file:
      - ./mongo/.env
    volumes:
      - ./mongo/data:/data/db
    ports:
      - ${MONGO_EXTERNAL_PORT}:27017
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
