name: AuditTrail

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8050:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge